language: objective-c
osx_image: xcode10.2

cache:
- bundler
- cocoapods

before_install:
- gem install bundler
- bundle install
- bundle exec pod install

script:
- xctool build -ColorPatterns.xcworkspace -scheme ColorPatterns -sdk iphonesimulator | xcpretty
- xcodebuild test -workspace ColorPatterns.xcworkspace -scheme ColorPatterns -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.2' | xcpretty
- bundle exec danger
