language: objective-c
osx_image: xcode11.3

script:
- bundle exec danger
- set -o pipefail && xcodebuild -workspace ColorPatterns.xcworkspace -scheme ColorPatterns -destination platform\=iOS\ Simulator,OS\=13.0,name\=iPhone\ 8 build test | xcpretty
